"============= Color and configuration Schema ====================
" The advantage in have a color schema is in the vimrc is that you
" do not needs to rely on the system because the color schema is
" inside the vimrc configuration file
" Vim color file
" Maintainer:  Douglas Quintiliano dos Santos <douglas.q.santos@gmail.com>
" Last Change: $Date: 2015/12/30 10:21 $

" cool help screens
" :he group-name
" :he highlight-groups
" :he cterm-colors
set background=dark
syntax on
if version > 580
" no guarantees for version 5.8 and below, but this makes it stop
" complaining
hi clear
if exists("syntax_on")
syntax reset
endif
endif
let g:colors_name="desert"

hi Normal   guifg=White guibg=grey20

" highlight groups
hi Cursor   guibg=khaki guifg=slategrey
"hi CursorIM
"hi Directory
"hi DiffAdd
"hi DiffChange
"hi DiffDelete
"hi DiffText
"hi ErrorMsg
hi VertSplit   guibg=#c2bfa5 guifg=grey50 gui=none
hi Folded   guibg=grey30 guifg=gold
hi FoldColumn  guibg=grey30 guifg=tan
hi IncSearch   guifg=slategrey guibg=khaki
"hi LineNr
hi ModeMsg  guifg=goldenrod
hi MoreMsg  guifg=SeaGreen
hi NonText  guifg=LightBlue guibg=grey30
hi Question guifg=springgreen
hi Search   guibg=peru guifg=wheat
hi SpecialKey  guifg=yellowgreen
hi StatusLine  guibg=#c2bfa5 guifg=black gui=none
hi StatusLineNC   guibg=#c2bfa5 guifg=grey50 gui=none
hi Title guifg=indianred
hi Visual   gui=none guifg=khaki guibg=olivedrab
"hi VisualNOS
hi WarningMsg  guifg=salmon
"hi WildMenu
"hi Menu
"hi Scrollbar
"hi Tooltip

" syntax highlighting groups
hi Comment  guifg=SkyBlue
hi Constant guifg=#ffa0a0
hi Identifier  guifg=palegreen
hi Statement   guifg=khaki
hi PreProc  guifg=indianred
hi Type     guifg=darkkhaki
hi Special  guifg=navajowhite
"hi Underlined
hi Ignore   guifg=grey40
"hi Error
hi Todo     guifg=orangered guibg=yellow2

" color terminal definitions
hi SpecialKey  ctermfg=darkgreen
hi NonText  cterm=bold ctermfg=darkblue
hi Directory   ctermfg=darkcyan
hi ErrorMsg cterm=bold ctermfg=7 ctermbg=1
hi IncSearch   cterm=NONE ctermfg=yellow ctermbg=green
hi Search   cterm=NONE ctermfg=grey ctermbg=blue
hi MoreMsg  ctermfg=darkgreen
hi ModeMsg  cterm=NONE ctermfg=brown
hi LineNr   ctermfg=3
hi Question ctermfg=green
hi StatusLine  cterm=bold,reverse
hi StatusLineNC cterm=reverse
hi VertSplit   cterm=reverse
hi Title ctermfg=5
hi Visual   cterm=reverse
hi VisualNOS   cterm=bold,underline
hi WarningMsg  ctermfg=1
hi WildMenu ctermfg=0 ctermbg=3
hi Folded   ctermfg=darkgrey ctermbg=NONE
hi FoldColumn  ctermfg=darkgrey ctermbg=NONE
hi DiffAdd  ctermbg=4
hi DiffChange  ctermbg=5
hi DiffDelete  cterm=bold ctermfg=4 ctermbg=6
hi DiffText cterm=bold ctermbg=1
hi Comment  ctermfg=darkcyan
hi Constant ctermfg=brown
hi Special  ctermfg=5
hi Identifier  ctermfg=6
hi Statement   ctermfg=3
hi PreProc  ctermfg=5
hi Type     ctermfg=2
hi Underlined  cterm=underline ctermfg=5
hi Ignore   cterm=bold ctermfg=7

" The block below shows the status bar with some information like
" Sample: ~/.vimrc [FORMAT=unix] [TYPE=VIM] [ASCII=034] [HEX=22] [line,column=0001,0001][0%] [LINES=227]
" show the ascii code about the character under the cursor and another stuffs
set statusline=%F%m%r%h%w\ [FORMAT=%{&ff}]\ [TYPE=%Y]\ [ASCII=\%03.3b]\ [HEX=\%02.2B]\ [line,column=%04l,%04v][%p%%]\ [LINES=%L]
set laststatus=2 " Show the status bar

" set up : enumaration, indentation, tab expansion to spaces
" show end parentheses, show rules and the current mode
"set ai et sm js
"set showcmd showmode
"set ruler
"syntax enable


"-----------------------------------------------------
" Highlight redundant whitespace and tabs.
highlight RedundantWhitespace ctermbg=red guibg=red
match RedundantWhitespace /\s\+$\| \+\ze\t/

" Enable file type detection
" Use the default filetype settings, so that mail gets 'tw' set to 72,
" 'cindent' is on in C files, etc.
" Also load indent files, to automatically do language-dependent indenting.
"filetype plugin indent on

" When enter in the insert mode changes the status bar color
" Change the status bar color depending on the mode
if version >= 700
        au InsertEnter * hi StatusLine term=reverse ctermbg=5 gui=undercurl guisp=Magenta
        au InsertLeave * hi StatusLine term=reverse ctermfg=0 ctermbg=2 gui=bold,reverse
endif

" Close automatically parentheses, square brackets and curly braces
"imap { {}<left>
"imap ( ()<left>
"imap [ []<left>

"When a new shell script is created automatically is append a header with some information that can be seen above
au BufEnter *.sh if getline(1) == "" | :call InsertHeadBash() | endif

"When a new ruby script is created automatically is append a header with some information that can be seen above
au BufEnter *.rb if getline(1) == "" | :call InsertHeadRuby() | endif

" Needs to be in the normal mode!
nmap <C-Down> ddp
nmap <C-Up> ddkP

" Remove doubled white lines
map ,d <esc>:%s/\(^\n\{2,}\)/\r/g<cr>})

" remove the space in the end of the line
map <F7> <esc>mz:%s/\s\+$//g<cr>`z

"  highlight the current word
nmap <s-f> :let @/="<C-r><C-w>"<CR>

" Allow reload the vim the new configuration from vimrc even
" the vimrc is editing
nmap <F12> :<C-u>source ~/.vimrc <BAR> echo "Vimrc reloaded!"<CR>
map ,u :source ~/.vimrc<CR>  " To reload the .vimrc
map ,v :e ~\.vimrc<CR>  " To edit the .vimrc


" Resize the window
" ALT+ right arrow and ALT + left arrow
map <M-right> <ESC>:resize +2 <CR>
map <M-left> <ESC>:resize -2 <CR>


"-----------------------------------------------------
" Automatically give executable permissions if filename ends in .sh, .pl or
" .cgi
" au BufWritePost *.sh,*.pl,*.cgi :!chmod a+x <afile>


"append the current time such eas %d/%m/%y %H:%M:%S in the current line
iab ,d <C-R>=strftime("%d/%m/%y %H:%M:%S")<CR>
"append the email in the current line
iab ,m <douglas.q.santos@gmail.com>
"
"" (strftime) is a built function
iab YDATE <C-R>=strftime("%d/%m/%y %H:%M:%S")<CR>
iab HDATE <C-R>=strftime("%d/%m/%y %H:%M:%S")<CR>
" Example: 30/12/15 11:16:02
"
" " Make sure if you typo the currect letter to save the file
cab W  w
cab Wq wq
cab wQ wq
cab WQ wq
cab Q  q

" Disable automatic comment insertion
" (https://vim.fandom.com/wiki/Disable_automatic_comment_insertion)
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

" Tab configuration
set ts=2
set sts=2
set et     "expand tabs to spaces
