"============= Color and configuration Schema ====================
"set background=dark    " Setting dark mode
colorscheme monokai "https://github.com/crusoexia/vim-monokai
"colorscheme gruvbox "https://github.com/morhetz/gruvbox
syntax on

set laststatus=2 " Show the status bar

" set up : enumaration, indentation, tab expansion to spaces
" show end parentheses, show rules and the current mode
"set ai et sm js
"set showcmd showmode
"set ruler
"syntax enable

"-----------------------------------------------------
" Highlight redundant whitespace and tabs.
highlight RedundantWhitespace ctermbg=red guibg=red
match RedundantWhitespace /\s\+$\| \+\ze\t/

" Enable file type detection
" Use the default filetype settings, so that mail gets 'tw' set to 72,
" 'cindent' is on in C files, etc.
" Also load indent files, to automatically do language-dependent indenting.
"filetype plugin indent on

" When enter in the insert mode changes the status bar color
" Change the status bar color depending on the mode
if version >= 700
        au InsertEnter * hi StatusLine term=reverse ctermbg=5 gui=undercurl guisp=Magenta
        au InsertLeave * hi StatusLine term=reverse ctermfg=0 ctermbg=2 gui=bold,reverse
endif

" Close automatically parentheses, square brackets and curly braces
"imap { {}<left>
"imap ( ()<left>
"imap [ []<left>

" Needs to be in the normal mode!
nmap <C-Down> ddp
nmap <C-Up> ddkP

" Remove doubled white lines
map ,d <esc>:%s/\(^\n\{2,}\)/\r/g<cr>})

" remove the space in the end of the line
map <F7> <esc>mz:%s/\s\+$//g<cr>`z

"  highlight the current word
nmap <s-f> :let @/="<C-r><C-w>"<CR>

" Allow reload the vim the new configuration from vimrc even
" the vimrc is editing
nmap <F12> :<C-u>source ~/.vimrc <BAR> echo "Vimrc reloaded!"<CR>
map ,u :source ~/.vimrc<CR>  " To reload the .vimrc
map ,v :e ~\.vimrc<CR>  " To edit the .vimrc


" " Make sure if you typo the currect letter to save the file
cab W  w
cab Wq wq
cab wQ wq
cab WQ wq
cab Q  q

" Disable automatic comment insertion
" (https://vim.fandom.com/wiki/Disable_automatic_comment_insertion)
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

" Tab configuration
set ts=2
set sts=2
set et     "expand tabs to spaces
